nba:
    nlayer: 2
    num_heads: 1
    hidden_dim: 64
    epoch: 1000
    lr: 0.001
    weight_decay: 0.00001
    tran_dropout: 0.3
    feat_dropout: 0.5
    prop_dropout: 0.5
    norm: 'layer'
    eps: [-0.2]
    eigk: 128
    decorrelation: 0.0
    decorrela_dim: 64
pokec_z:
    nlayer: 2
    num_heads: 1
    hidden_dim: 128
    epoch: 500
    lr: 0.001
    weight_decay: 0.00001
    tran_dropout: 0.5
    feat_dropout: 0.5
    prop_dropout: 0.5
    norm: 'layer'
    eps: [-0.5]
    eigk: 256
    decorrelation: 1.0
    decorrela_dim: 128
pokec_n:
    nlayer: 2
    num_heads: 1
    hidden_dim: 128
    epoch: 500
    lr: 0.001
    weight_decay: 0.00001
    tran_dropout: 0.3
    feat_dropout: 0.6
    prop_dropout: 0.6
    norm: 'layer'
    eps: [-0.4]
    eigk: 128
    decorrelation: 10.0
    decorrela_dim: 128
