nba:
    nlayer: 2
    num_heads: 1
    hidden_dim: 64
    epoch: 1000
    lr: 0.001
    weight_decay: 0.00001
    tran_dropout: 0.3
    feat_dropout: 0.5
    prop_dropout: 0.5
    norm: 'layer'
    eps: [-0.2]
    eigk: 128
    decorrelation: 0.0
    decorrela_dim: 64
    patience: 5
    label_number: 100
    sens_number: 50
    ms_decor: 0.0
pokec_z:
    nlayer: 3
    num_heads: 1
    hidden_dim: 128
    epoch_fit: 500
    epoch_debias: 500
    lr: 0.001
    weight_decay: 0.00001
    tran_dropout: 0.5
    feat_dropout: 0.5
    prop_dropout: 0.5
    norm: 'layer'
    eps: [-0.5]
    eigk: 256
    decorrelation: 1.0
    orthogonality: 10.0
    decorrela_dim: 128
    patience: 5
    shd_filter: 'F'
    shd_trans: 'F'
    label_number: 500
    sens_number: 200
    ms_decor: 0.0
pokec_n:
    nlayer: 2
    num_heads: 1
    hidden_dim: 128
    epoch_fit: 1000
    epoch_debias: 5000
    lr: 0.001
    weight_decay: 0.00001
    tran_dropout: 0.3
    feat_dropout: 0.6
    prop_dropout: 0.6
    norm: 'layer'
    eps: [-0.5]
    eigk: 128
    decorrelation: 10.0
    orthogonality: 10.0
    decorrela_dim: 128
    patience: 5
    shd_filter: 'F'
    shd_trans: 'F'
    label_number: 500
    sens_number: 200
    ms_decor: 0.1
    ms_bank: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4.0]
credit:
    nlayer: 2
    num_heads: 1
    hidden_dim: 128
    epoch_fit: 1000
    epoch_debias: 500
    lr: 0.001
    weight_decay: 0.00001
    tran_dropout: 0.5
    feat_dropout: 0.5
    prop_dropout: 0.5
    norm: 'na'
    eps: [-0.5]
    eigk: 128
    decorrelation: 1.0
    orthogonality: 500.0
    decorrela_dim: 128
    patience: 5
    shd_filter: 'F'
    shd_trans: 'F'
    label_number: 6000
    sens_number: -1
    ms_decor: 0.5
    ms_bank: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4.0]
german:
    nlayer: 2
    num_heads: 1
    hidden_dim: 128
    epoch_fit: 500
    epoch_debias: 500
    lr: 0.001
    weight_decay: 0.00001
    tran_dropout: 0.5
    feat_dropout: 0.5
    prop_dropout: 0.5
    norm: 'na'
    eps: [-0.5]
    eigk: 128
    decorrelation: 1.0
    orthogonality: 200.0
    decorrela_dim: 128
    patience: 5
    shd_filter: 'F'
    shd_trans: 'F'
    label_number: 100
    sens_number: -1
    ms_decor: 0.0
bail:
    nlayer: 3
    num_heads: 1
    hidden_dim: 128
    epoch: 500
    lr: 0.001
    weight_decay: 0.00001
    tran_dropout: 0.5
    feat_dropout: 0.5
    prop_dropout: 0.5
    norm: 'na'
    eps: [-0.5]
    eigk: 256
    decorrelation: 1.0
    orthogonality: 10.0
    decorrela_dim: 128
    patience: 5
    shd_filter: 'F'
    shd_trans: 'F'
    label_number: 100
    sens_number: -1
    ms_decor: 0.0
income:
    nlayer: 3
    num_heads: 1
    hidden_dim: 64
    epoch_fit: 500
    epoch_debias: 500
    lr: 0.001
    weight_decay: 0.00001
    tran_dropout: 0.5
    feat_dropout: 0.5
    prop_dropout: 0.5
    norm: 'na'
    eps: [-0.5]
    eigk: 64
    decorrelation: 1.0
    orthogonality: 100.0
    decorrela_dim: 128
    patience: 5
    shd_filter: 'F'
    shd_trans: 'F'
    label_number: 3000
    sens_number: -1
    ms_decor: 100.0
