nba:
    nlayer: 1
    num_heads: 1
    hidden_dim: 128
    epoch: 2000
    lr: 0.001
    weight_decay: 0.00001
    feat_dropout: 0.5
    norm: 'na'
pokec_z:
    nlayer: 2
    num_heads: 1
    hidden_dim: 128
    epoch: 500
    lr: 0.001
    weight_decay: 0.00001
    feat_dropout: 0.5
    norm: 'na'
    decorrelation: 1.0
    decorrela_dim: 128
pokec_n:
    nlayer: 2
    num_heads: 1
    hidden_dim: 128
    epoch: 1000
    lr: 0.001
    weight_decay: 0.00001
    feat_dropout: 0.5
    norm: 'na'
    decorrelation: 1.0
    decorrela_dim: 128
credit:
    nlayer: 2
    num_heads: 1
    hidden_dim: 128
    epoch: 500
    lr: 0.001
    weight_decay: 0.00001
    feat_dropout: 0.5
    norm: 'na'
    decorrelation: 1.0
    orthogonality: 0.0
    decorrela_dim: 128