nba:
    nlayer: 1
    num_heads: 1
    hidden_dim: 128
    epoch: 2000
    lr: 0.001
    weight_decay: 0.00001
    feat_dropout: 0.5
    norm: 'na'
    patience: 5
pokec_z:
    nlayer: 2
    num_heads: 1
    hidden_dim: 128
    epoch_fit: 500
    epoch_debias: 500
    lr: 0.001
    weight_decay: 0.00001
    feat_dropout: 0.5
    norm: 'na'
    decorrelation: 1.0
    orthogonality: 10.0
    decorrela_dim: 128
    patience: 5
pokec_n:
    nlayer: 2
    num_heads: 1
    hidden_dim: 128
    epoch_fit: 500
    epoch_debias: 500
    lr: 0.001
    weight_decay: 0.00001
    feat_dropout: 0.5
    norm: 'na'
    decorrelation: 1.0
    orthogonality: 10.0
    decorrela_dim: 128
    patience: 5
credit:
    nlayer: 2
    num_heads: 1
    hidden_dim: 128
    epoch_fit: 500
    epoch_debias: 500
    lr: 0.001
    weight_decay: 0.00001
    feat_dropout: 0.5
    norm: 'na'
    decorrelation: 1.0
    orthogonality: 0.0
    decorrela_dim: 128
    patience: 5
german:
    nlayer: 2
    num_heads: 1
    hidden_dim: 128
    epoch_fit: 500
    epoch_debias: 500
    lr: 0.001
    weight_decay: 0.00001
    feat_dropout: 0.5
    norm: 'na'
    decorrelation: 1.0
    orthogonality: 100.0
    decorrela_dim: 128
    patience: 5
income:
    nlayer: 2
    num_heads: 1
    hidden_dim: 128
    epoch_fit: 500
    epoch_debias: 500
    lr: 0.001
    weight_decay: 0.00001
    tran_dropout: 0.5
    feat_dropout: 0.5
    prop_dropout: 0.5
    norm: 'na'
    eps: [-0.5]
    decorrelation: 1.0
    orthogonality: 200
    decorrela_dim: 128
    patience: 5
