nba:
    nlayer: 2
    num_heads: 1
    hidden_dim: 64
    filter_dim: 64
    epoch: 1000
    lr: 0.001
    weight_decay: 0.00001
    tran_dropout: 0.3
    feat_dropout: 0.5
    prop_dropout: 0.5
    eps: [-0.2]
    eigk: 128
    signal_dim: 64
    patience: 5
    temp: 1.0
    adver: 0.0
    init_mean: 0.0
    init_std: 0.01
    label_number: 100
    sens_number: 50
pokec_z:
    nlayer: 3
    num_heads: 1
    hidden_dim: 128
    filter_dim: 128
    epoch: 500
    lr: 0.001
    weight_decay: 0.00001
    tran_dropout: 0.5
    feat_dropout: 0.5
    prop_dropout: 0.5
    eps: [-0.5]
    eigk: 256
    signal_dim: 128
    patience: 5
    temp: 1.0
    adver: 0.0
    init_mean: 0.0
    init_std: 0.01
    label_number: 500
    sens_number: 200
pokec_n:
    nlayer: 2
    num_heads: 1
    hidden_dim: 128
    filter_dim: 128
    epoch: 500
    lr: 0.001
    weight_decay: 0.00001
    tran_dropout: 0.3
    feat_dropout: 0.6
    prop_dropout: 0.6
    eps: [-0.5]
    eigk: 256
    signal_dim: 128
    patience: 5
    temp: 1.0
    adver: 0.0
    init_mean: 0.0
    init_std: 0.01
    label_number: 500
    sens_number: 200
credit:
    nlayer: 3
    num_heads: 1
    hidden_dim: 128
    filter_dim: 128
    epoch: 500
    lr: 0.001
    weight_decay: 0.00001
    tran_dropout: 0.5
    feat_dropout: 0.5
    prop_dropout: 0.5
    eps: [-0.5]
    eigk: 128
    signal_dim: 128
    patience: 5
    temp: 1.0
    adver: 20.0
    init_mean: 0.0
    init_std: 0.01
    label_number: 6000
    sens_number: -1
german:
    nlayer: 2
    num_heads: 1
    hidden_dim: 128
    filter_dim: 128
    epoch: 500
    lr: 0.001
    weight_decay: 0.00001
    tran_dropout: 0.5
    feat_dropout: 0.5
    prop_dropout: 0.5
    eps: [-0.5]
    eigk: 128
    signal_dim: 128
    patience: 5
    temp: 1.0
    adver: 0.0
    init_mean: 0.0
    init_std: 0.01
    label_number: 100
    sens_number: -1
bail:
    nlayer: 3
    num_heads: 1
    hidden_dim: 128
    filter_dim: 128
    epoch: 500
    lr: 0.001
    weight_decay: 0.00001
    tran_dropout: 0.5
    feat_dropout: 0.5
    prop_dropout: 0.5
    eps: [-0.5]
    eigk: 256
    signal_dim: 128
    patience: 5
    temp: 1.0
    adver: 0.0
    init_mean: 0.0
    init_std: 0.01
    label_number: 100
    sens_number: -1
income:
    nlayer: 3
    num_heads: 1
    hidden_dim: 64
    filter_dim: 128
    epoch: 500
    lr: 0.001
    weight_decay: 0.00001
    tran_dropout: 0.5
    feat_dropout: 0.5
    prop_dropout: 0.5
    eps: [-0.5]
    eigk: 64
    signal_dim: 128
    patience: 5
    temp: 1.0
    adver: 100.0
    init_mean: 1.0
    init_std: 0.1
    label_number: 3000
    sens_number: -1
