nba:
    nlayer: 2
    num_heads: 1
    hidden_dim: 64
    epoch: 1000
    lr: 0.001
    weight_decay: 0.00001
    tran_dropout: 0.3
    feat_dropout: 0.5
    prop_dropout: 0.5
    norm: 'none'
    eps: [-0.2]
    eigk: 128
    signal_dim: 64
    patience: 5
    label_number: 100
    sens_number: 50
pokec_z:
    nlayer: 3
    num_heads: 1
    hidden_dim: 128
    epoch_fit: 500
    epoch_debias: 5000
    lr: 0.001
    weight_decay: 0.00001
    tran_dropout: 0.5
    feat_dropout: 0.5
    prop_dropout: 0.5
    norm: 'none'
    eps: [-0.5]
    eigk: 256
    signal_dim: 128
    patience: 5
    shd_filter: 'F'
    shd_trans: 'F'
    label_number: 999999
    sens_number: 999999
    align_weight: 0.001
pokec_n:
    nlayer: 2
    num_heads: 1
    hidden_dim: 128
    epoch_fit: 500
    epoch_debias: 5000
    lr: 0.001
    weight_decay: 0.00001
    tran_dropout: 0.3
    feat_dropout: 0.6
    prop_dropout: 0.6
    norm: 'none'
    eps: [-0.5]
    eigk: 256
    signal_dim: 128
    patience: 5
    shd_filter: 'F'
    shd_trans: 'F'
    label_number: 999999
    sens_number: 999999
    align_weight: 1.0
    align_mode: 'l1'
credit:
    nlayer: 2
    num_heads: 1
    hidden_dim: 128
    epoch_fit: 500
    epoch_debias: 500
    lr: 0.001
    weight_decay: 0.00001
    tran_dropout: 0.5
    feat_dropout: 0.5
    prop_dropout: 0.5
    norm: 'none'
    eps: [-0.5]
    eigk: 128
    signal_dim: 128
    patience: 20
    shd_filter: 'F'
    shd_trans: 'F'
    label_number: 6000
    sens_number: -1
    align_weight: 1.0
    align_mode: 'l2'
german:
    nlayer: 2
    num_heads: 1
    hidden_dim: 128
    epoch_fit: 500
    epoch_debias: 500
    lr: 0.001
    weight_decay: 0.00001
    tran_dropout: 0.5
    feat_dropout: 0.5
    prop_dropout: 0.5
    norm: 'none'
    eps: [-0.5]
    eigk: 128
    signal_dim: 128
    patience: 20
    shd_filter: 'F'
    shd_trans: 'F'
    label_number: 100
    sens_number: -1
    align_weight: 1.0
    align_mode: 'l2'
bail:
    nlayer: 3
    num_heads: 1
    hidden_dim: 128
    epoch: 500
    lr: 0.001
    weight_decay: 0.00001
    tran_dropout: 0.5
    feat_dropout: 0.5
    prop_dropout: 0.5
    norm: 'none'
    eps: [-0.5]
    eigk: 256
    signal_dim: 128
    patience: 5
    shd_filter: 'F'
    shd_trans: 'F'
    label_number: 100
    sens_number: -1
income:
    nlayer: 2
    num_heads: 1
    hidden_dim: 128
    epoch_fit: 500
    epoch_debias: 100
    lr: 0.001
    weight_decay: 0.00001
    tran_dropout: 0.5
    feat_dropout: 0.5
    prop_dropout: 0.5
    norm: 'none'
    eps: [-0.5]
    eigk: 128
    signal_dim: 128
    patience: 10
    shd_filter: 'F'
    shd_trans: 'F'
    label_number: 3000
    sens_number: -1
    align_weight: 1.0
    align_mode: 'l2'
